### ISSUE TITLE
Update GUI for reading multiple MMFE at once

### ISSUE THREAD

**Issue by alexandertuna** [alexandertuna/MMFE8Readout#3]
This will take some effort.

**Comment by alexandertuna** [comment]
In progress at [python/dev/tuna](https://github.com/alexandertuna/MMFE8Readout/tree/master/python/dev/tuna)

**Comment by giakov** [comment]
we have adapted the qt software to read very efficiently and with unlimited number of VMMs so if you let us know the data format we can support the MMFE8 also

**Comment by alexandertuna** [comment]
Hi George! Awesome. Right now I am developing within the python code AZ has already written for reading out the MMFE8. The outputs are simple text files, though extending this to ROOT trees will not be difficult.

Can the qt code be extended to communicate with the MMFE8s? That would also be great. If you want to put the code on this repo, I'm sure it would be welcome (maybe a qt/ directory).

**Comment by giakov** [comment]
Hey Alex, the Qt code builds already events in ROOT and has much more features, it's not only dumping hits. You can find it on the nsw/elx svn. I will update it such that communicates with MMFE8s but the board firmware should be adjusted to the requirements first.
